CREATE TABLE "ACESSO_EMPRESA" (
    "EMP_ID" TEXT NOT NULL,
    "EMP_NOME" TEXT NOT NULL,
    "EMP_EMAIL" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "ACESSO_EMPRESA_pkey" PRIMARY KEY ("EMP_ID")
);

CREATE TABLE "ACESSO_PAPEL" (
    "PAP_ID" TEXT NOT NULL,
    "PAP_NOME" TEXT NOT NULL,
    "PAP_DESCRICAO" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "ACESSO_PAPEL_pkey" PRIMARY KEY ("PAP_ID")
);

CREATE TABLE "ACESSO_PERMISSAO" (
    "PRM_ID" TEXT NOT NULL,
    "PRM_NOME" TEXT NOT NULL,
    "PRM_DESCRICAO" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "ACESSO_PERMISSAO_pkey" PRIMARY KEY ("PRM_ID")
);

CREATE TABLE "ACESSO_PAP_PRM" (
    "PPE_ID" SERIAL NOT NULL,
    "PRM_ID" TEXT NOT NULL,
    "PAP_ID" TEXT NOT NULL,

    CONSTRAINT "ACESSO_PAP_PRM_pkey" PRIMARY KEY ("PPE_ID")
);

CREATE TABLE "ACESSO_USUARIO" (
    "USU_ID" TEXT NOT NULL,
    "USU_NOME" TEXT NOT NULL,
    "USU_TELEFONE" TEXT NOT NULL DEFAULT '',
    "USU_CPF" TEXT NOT NULL DEFAULT '',
    "USU_CNPJ" TEXT NOT NULL DEFAULT '',
    "USU_USUARIO" TEXT NOT NULL DEFAULT '',
    "USU_ACESSO" TEXT NOT NULL,
    "USU_EMAIL" TEXT NOT NULL,
    "USU_SENHA_HASH" TEXT NOT NULL,
    "USU_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "USU_MFA_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "USU_MFA_METODOS" TEXT[] NOT NULL DEFAULT ARRAY['EMAIL', 'AUTHENTICATOR']::TEXT[],
    "USU_MFA_METODO_PADRAO" TEXT NOT NULL DEFAULT 'EMAIL',
    "USU_TOTP_SECRET" TEXT NOT NULL DEFAULT '',
    "USU_DEVE_TROCAR_SENHA" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "ACESSO_USUARIO_pkey" PRIMARY KEY ("USU_ID")
);

CREATE TABLE "ACESSO_USU_EMP_PAP" (
    "UEP_ID" SERIAL NOT NULL,
    "USU_ID" TEXT NOT NULL,
    "EMP_ID" TEXT NOT NULL,
    "PAP_ID" TEXT NOT NULL,

    CONSTRAINT "ACESSO_USU_EMP_PAP_pkey" PRIMARY KEY ("UEP_ID")
);

CREATE TABLE "NOTIFICACAO" (
    "NTF_ID" TEXT NOT NULL,
    "USU_ID" TEXT NOT NULL,
    "NTF_TITULO" TEXT NOT NULL,
    "NTF_MENSAGEM" TEXT NOT NULL,
    "NTF_LIDA" BOOLEAN NOT NULL DEFAULT false,
    "NTF_DATA" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NOTIFICACAO_pkey" PRIMARY KEY ("NTF_ID")
);

CREATE TABLE "ACESSO_AUTH_LOG" (
    "LOG_ID" TEXT NOT NULL,
    "LOG_DATA" TIMESTAMP(3) NOT NULL,
    "LOG_EVENTO" TEXT NOT NULL,
    "USU_ID" TEXT,
    "EMP_ID" TEXT,
    "IDENTIFICADOR" TEXT NOT NULL DEFAULT '',
    "IP" TEXT NOT NULL DEFAULT '',
    "SUCESSO" BOOLEAN NOT NULL,
    "MENSAGEM" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "ACESSO_AUTH_LOG_pkey" PRIMARY KEY ("LOG_ID")
);

CREATE UNIQUE INDEX "ACESSO_PERMISSAO_PRM_NOME_key" ON "ACESSO_PERMISSAO"("PRM_NOME");
CREATE UNIQUE INDEX "ACESSO_PAP_PRM_PRM_ID_PAP_ID_key" ON "ACESSO_PAP_PRM"("PRM_ID", "PAP_ID");
CREATE UNIQUE INDEX "ACESSO_USU_EMP_PAP_USU_ID_EMP_ID_key" ON "ACESSO_USU_EMP_PAP"("USU_ID", "EMP_ID");

ALTER TABLE "ACESSO_PAP_PRM" ADD CONSTRAINT "ACESSO_PAP_PRM_PRM_ID_fkey" FOREIGN KEY ("PRM_ID") REFERENCES "ACESSO_PERMISSAO"("PRM_ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ACESSO_PAP_PRM" ADD CONSTRAINT "ACESSO_PAP_PRM_PAP_ID_fkey" FOREIGN KEY ("PAP_ID") REFERENCES "ACESSO_PAPEL"("PAP_ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ACESSO_USU_EMP_PAP" ADD CONSTRAINT "ACESSO_USU_EMP_PAP_USU_ID_fkey" FOREIGN KEY ("USU_ID") REFERENCES "ACESSO_USUARIO"("USU_ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ACESSO_USU_EMP_PAP" ADD CONSTRAINT "ACESSO_USU_EMP_PAP_EMP_ID_fkey" FOREIGN KEY ("EMP_ID") REFERENCES "ACESSO_EMPRESA"("EMP_ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ACESSO_USU_EMP_PAP" ADD CONSTRAINT "ACESSO_USU_EMP_PAP_PAP_ID_fkey" FOREIGN KEY ("PAP_ID") REFERENCES "ACESSO_PAPEL"("PAP_ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NOTIFICACAO" ADD CONSTRAINT "NOTIFICACAO_USU_ID_fkey" FOREIGN KEY ("USU_ID") REFERENCES "ACESSO_USUARIO"("USU_ID") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ACESSO_AUTH_LOG" ADD CONSTRAINT "ACESSO_AUTH_LOG_USU_ID_fkey" FOREIGN KEY ("USU_ID") REFERENCES "ACESSO_USUARIO"("USU_ID") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ACESSO_AUTH_LOG" ADD CONSTRAINT "ACESSO_AUTH_LOG_EMP_ID_fkey" FOREIGN KEY ("EMP_ID") REFERENCES "ACESSO_EMPRESA"("EMP_ID") ON DELETE SET NULL ON UPDATE CASCADE;
